services:
  app_db:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data_tavern:/bitnami/postgresql"
    environment:
      POSTGRES_DB: stack_tavern
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8081:8080

  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    depends_on:
      - postgresql
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
    driver: local
  postgresql_data_tavern:
    driver: local
